[package]
name = "fake-google"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
ports.workspace = true
testkit.workspace = true
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
mail-parser.workspace = true
time.workspace = true
uuid.workspace = true
url.workspace = true
async-trait.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio.workspace = true
reqwest.workspace = true
base64.workspace = true
tower = { version = "0.5", features = ["util"] }
