#!/usr/bin/env python3
"""Loopback-only Flutter web host and same-origin API proxy for T-1101a.

HTTP framing and hop-by-hop headers are regenerated by the proxy; all
end-to-end upstream headers, including repeated Set-Cookie, are retained.
"""

import argparse
import fnmatch
import http.client
import json
import mimetypes
from pathlib import Path
import re
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import unquote, urlsplit
from typing import cast


HOP_HEADERS = {"connection", "keep-alive", "proxy-authenticate", "proxy-authorization",
               "te", "trailer", "transfer-encoding", "upgrade"}


def glob_matches(pattern, path):
    """Match Firebase-style path globs: *, **, ?, classes and brace alternatives."""
    brace = re.search(r"\{([^{}]+)\}", pattern)
    if brace:
        return any(glob_matches(pattern[:brace.start()] + item + pattern[brace.end():], path)
                   for item in brace.group(1).split(","))
    parts = pattern.lstrip("/").split("/")
    segments = path.lstrip("/").split("/")

    def match(pattern_index, path_index):
        if pattern_index == len(parts):
            return path_index == len(segments)
        if parts[pattern_index] == "**":
            return any(match(pattern_index + 1, end)
                       for end in range(path_index, len(segments) + 1))
        return (path_index < len(segments)
                and fnmatch.fnmatchcase(segments[path_index], parts[pattern_index])
                and match(pattern_index + 1, path_index + 1))

    return match(0, 0)


def hop_headers(headers):
    excluded = set(HOP_HEADERS)
    for value in headers.get_all("Connection", []):
        excluded.update(item.strip().lower() for item in value.split(","))
    return excluded


class HostServer(ThreadingHTTPServer):
    daemon_threads = True

    def __init__(self, root, firebase_json, api, port=0):
        self.root = Path(root).resolve(strict=True)
        self.rules = json.loads(Path(firebase_json).read_text())["hosting"].get("headers", [])
        parsed = urlsplit(api)
        if (parsed.scheme not in ("http", "https") or not parsed.hostname
                or parsed.username or parsed.password or parsed.query or parsed.fragment
                or parsed.path not in ("", "/")):
            raise ValueError("--api must be an HTTP(S) origin without credentials")
        self.api = api
        if not self.root.is_dir():
            raise ValueError("--root must be a directory")
        super().__init__(("127.0.0.1", port), HostHandler)


def create_server(root, firebase_json, api, port=0):
    return HostServer(root, firebase_json, api, port)


class HostHandler(BaseHTTPRequestHandler):
    @property
    def host(self):
        return cast(HostServer, self.server)

    # HTTP/1.0 closes every response, including rejected requests with unread bodies.
    # Do not log request paths, cookies, or other sensitive browser data.
    def log_message(self, format, *args):
        pass

    def end_headers(self):
        for rule in self.host.rules:
            if glob_matches(rule["source"], getattr(self, "header_path", "/")):
                for header in rule["headers"]:
                    self.send_header(header["key"], header["value"])
        super().end_headers()

    def fail(self, status, message):
        body = (message + "\n").encode()
        self.send_response(status)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def handle_request(self):
        self.header_path = "/"
        try:
            parsed = urlsplit(self.path)
            if parsed.scheme or parsed.netloc or parsed.fragment or not parsed.path.startswith("/"):
                self.fail(400, "Invalid request path")
                return
            path = unquote(parsed.path, errors="strict")
        except (ValueError, UnicodeError):
            self.fail(400, "Invalid request path")
            return
        self.header_path = path
        if "\\" in path or any(ord(character) < 32 or ord(character) == 127 for character in path):
            self.fail(400, "Invalid request path")
            return
        if any(part.startswith(".") for part in path.split("/") if part):
            self.fail(403, "Forbidden path")
            return
        if path.startswith("/api/"):
            self.proxy()
        elif self.command in ("GET", "HEAD"):
            self.static(path)
        else:
            self.fail(405, "Method not allowed")

    def static(self, path):
        candidate = (self.host.root / path.lstrip("/")).resolve()
        if (not candidate.is_relative_to(self.host.root)
                or any(part.startswith(".") for part in candidate.relative_to(self.host.root).parts)):
            self.fail(403, "Forbidden path")
            return
        if not candidate.is_file():
            candidate = (self.host.root / "index.html").resolve()
            self.header_path = "/index.html"
        if (not candidate.is_relative_to(self.host.root)
                or any(part.startswith(".") for part in candidate.relative_to(self.host.root).parts)):
            self.fail(403, "Forbidden path")
            return
        try:
            body = candidate.read_bytes()
        except OSError:
            self.fail(404, "File not found")
            return
        # Fixed web MIME types avoid host-dependent wasm/JS mime databases.
        types = {".html": "text/html; charset=utf-8", ".js": "text/javascript",
                 ".mjs": "text/javascript", ".css": "text/css", ".json": "application/json",
                 ".wasm": "application/wasm", ".png": "image/png", ".jpg": "image/jpeg",
                 ".jpeg": "image/jpeg", ".svg": "image/svg+xml", ".ico": "image/x-icon",
                 ".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf",
                 ".webmanifest": "application/manifest+json"}
        self.send_response(200)
        content_type = (types.get(candidate.suffix.lower())
                        or mimetypes.guess_type(candidate.name)[0] or "application/octet-stream")
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def proxy(self):
        lengths = self.headers.get_all("Content-Length", [])
        if (self.headers.get("Transfer-Encoding") is not None or len(lengths) > 1
                or (lengths and not re.fullmatch(r"[0-9]+", lengths[0]))):
            self.fail(400, "Invalid request framing")
            return
        length = int(lengths[0]) if lengths else 0
        # Browser JSON requests are small; cap reads to prevent local resource exhaustion.
        if length > 16 * 1024 * 1024:
            self.fail(413, "Request body too large")
            return
        self.connection.settimeout(10)
        try:
            body = self.rfile.read(length)
        except (OSError, TimeoutError):
            self.fail(400, "Incomplete request body")
            return
        if len(body) != length:
            self.fail(400, "Incomplete request body")
            return
        parsed = urlsplit(self.host.api)
        if parsed.hostname is None:
            self.fail(502, "API unavailable")
            return
        connection_class = (http.client.HTTPSConnection if parsed.scheme == "https"
                            else http.client.HTTPConnection)
        connection = connection_class(parsed.hostname, parsed.port, timeout=10)
        try:
            connection.putrequest(self.command, self.path, skip_accept_encoding=True)
            excluded = hop_headers(self.headers) | {"host", "content-length", "x-forwarded-for"}
            for key, value in self.headers.items():
                if key.lower() not in excluded:
                    connection.putheader(key, value)
            connection.putheader("X-Forwarded-For", "127.0.0.1")
            connection.putheader("Content-Length", str(length))
            connection.endheaders(body)
            response = connection.getresponse()
            data = response.read()
            headers = response.getheaders()
            excluded = hop_headers(response.headers) | {"content-length"}
        except (OSError, http.client.HTTPException, ValueError):
            self.fail(502, "API unavailable")
            return
        finally:
            connection.close()
        self.send_response_only(response.status, response.reason)
        for key, value in headers:
            if key.lower() not in excluded:
                self.send_header(key, value)
        if self.command == "HEAD":
            if response.headers.get("Content-Length") is not None:
                self.send_header("Content-Length", response.headers["Content-Length"])
        elif response.status not in (204, 304) and response.status >= 200:
            self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(data)

    do_GET = do_HEAD = do_POST = do_PUT = do_PATCH = do_DELETE = do_OPTIONS = handle_request


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", required=True, type=Path)
    parser.add_argument("--firebase-json", required=True, type=Path)
    parser.add_argument("--api", required=True)
    parser.add_argument("--port-file", required=True, type=Path)
    parser.add_argument("--port", type=int, default=0)
    args = parser.parse_args()
    with create_server(args.root, args.firebase_json, args.api, args.port) as server:
        # Publish only after bind; atomic replacement keeps readers from seeing partial text.
        pending = args.port_file.with_name(args.port_file.name + ".pending")
        pending.write_text(str(server.server_port) + "\n")
        pending.replace(args.port_file)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass


if __name__ == "__main__":
    main()
