[package]
name = "domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
time.workspace = true
url.workspace = true
thiserror.workspace = true
html5ever.workspace = true
unicode-segmentation.workspace = true
percent-encoding = "2"
regex = "1"
whatlang = "0.18"
tracing = "0.1"

[lints]
workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
unicode-segmentation.workspace = true
