[package]
name = "worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
domain.workspace = true
ports.workspace = true
obs.workspace = true
time.workspace = true

[dev-dependencies]
serde_json.workspace = true
testkit.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
